name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - MLOps_Dev_Branch_2  # Trigger action on push to this branch
  pull_request:
    branches:
      - MLOps_Dev_Branch_2  # Trigger action for PRs to this branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python for the project (using Python 3.9 as per requirement)
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify Python version you use

    # Step 3: Install project dependencies (from requirements.txt)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Tests on your code with pytest
    - name: Run Tests
      run: |
        pytest tests/test_model.py  # Run the test script

    # Step 5: Train the model and save the model
    - name: Train and Save Model
      run: |
        python model/train.py  # Train and save model to file
    
    # Step 6: (Optional) Upload model file or other artifacts if needed
    - name: Upload trained model
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: trained_model.pkl  # Uploads the trained model
