name: MLOps CI Pipeline

on:
  push:
    branches:
      - MLOps_Dev_Branch_2
  pull_request:

jobs:
  ci_pipeline:
    name: CI/CD Pipeline
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set PYTHONPATH environment variable
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      # Run linting
      - name: Run Flake8 Linting
        run: flake8 model/

      # Run tests
      - name: Run Pytest
        run: pytest tests/
